name: ${project.name}
main: com.bigbrainiac10.simplehelpop.SimpleHelpOp
version: ${project.version}
author: bigbrainiac10
authors: [Maxopoly]
depend: [CivModCore]
softdepend: [NameLayer]
description: Allow players to request help.
commands:
  helpop:
    permission: simplehelpop.requesthelp
  viewhelp:
    permission: simplehelpop.replyhelp
permissions:
  simplehelpop.requesthelp:
    description: Allow a player to request help
    default: true
  simplehelpop.replyhelp:
    description: Allow a player to reply to a question
    default: op
  simplehelpop.*:
    description: Grant all simplehelpop permissions
    default: op
    children:
      simplehelpop.replyhelp: true
      simplehelpop.requesthelp: true